"""add Department


Revision ID: 241303aaaf18
Revises: c8ab7a5089b6
Create Date: 2024-10-17 18:39:30.899306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241303aaaf18'
down_revision = 'c8ab7a5089b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
